Repository appnexus/lucid, pull requests merged in 2018-04, with the labels that each got.

#921 Add some convenience scripts to quickly get started
  scripts/create-component-dev.sh
  scripts/create-component-docs.sh
  scripts/create-component-source.sh
Labels: in progress, quality, semver-none

#922 Selector option formatting
  .storybook/lucid-docs-addon/index.js
  docs/examples/SearchableMultiSelect.stories.js
  docs/examples/SearchableMultiSelect/WithFormattedOptions.js
  docs/examples/SearchableSelect.stories.js
  docs/examples/SearchableSelect/WithFormattedOptions.js
  docs/examples/SingleSelect.stories.js
  docs/examples/SingleSelect/WithFormattedOptions.js
  docs/examples/Underline.stories.js
  docs/examples/Underline/WithDefaults.js
  docs/examples/Underline/WithRegexMatch.js
  docs/examples/Underline/WithStringMatch.js
  src/components/DropMenu/DropMenu.jsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.spec.jsx
  src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.jsx.snap
  src/components/SearchableSelect/SearchableSelect.jsx
  src/components/SearchableSelect/SearchableSelect.spec.jsx
  src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.jsx.snap
  src/components/SingleSelect/SingleSelect.jsx
  src/components/SingleSelect/SingleSelect.spec.jsx
  src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
  src/components/Underline/Underline.jsx
  src/components/Underline/Underline.spec.jsx
  src/components/Underline/__snapshots__/Underline.spec.jsx.snap
  src/index.js
  src/util/generic-tests.jsx
  src/util/text-manipulation.js
  src/util/text-manipulation.spec.js
Labels: in progress, semver-minor

#923 Anxr1554 optimization
  .babelrc
  .gitignore
  package.json
  yarn.lock
Labels: in progress, semver-minor

#924 create-component script
  CONTRIBUTING.md
  README.md
  docs/index.stories.js
  package.json
  scripts/create-component-exports-transform.js
  scripts/create-component-exports.sh
  scripts/create-component-less.sh
  scripts/create-component.sh
  src/index.js
Labels: in progress, quality
