Repository appnexus/lucid, pull requests merged in 2018-02, with the labels that each got.

#895 Publish docgen json
  gulp/docs.js
  gulpfile.js
  package.json
  src/util/component-types.js
  yarn.lock
Labels: documentation, semver-none

#898 Unmount Portal at DOM node before removing it
  src/components/Portal/Portal.jsx
Labels: semver-patch

#896 Fix initial state bug
  src/util/state-management.js
Labels: semver-patch

#897 Add fine grained tick control
  src/components/LineChart/LineChart.jsx
  src/components/LineChart/__snapshots__/LineChart.spec.jsx.snap
  src/components/LineChart/examples/16.fine-grained-ticks.jsx
Labels: semver-minor

#899 optimize performance of bar charts
  package.json
  src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
  src/components/BarChart/examples/13.many-bars.jsx
  src/components/Bars/Bars.jsx
  src/components/Bars/Bars.spec.jsx
  src/components/Bars/__snapshots__/Bars.spec.jsx.snap
  yarn.lock
Labels: semver-patch

#894 Np
  package.json
  yarn.lock
Labels: semver-none

#903 fix secondary button size in `SplitButton`
  src/components/SplitButton/SplitButton.jsx
  src/components/SplitButton/__snapshots__/SplitButton.spec.jsx.snap
  src/components/SplitButton/examples/4.sizes.jsx
Labels: semver-patch

#906 lucid-905: Make helpicon darker, change hover color as well.
  src/components/Icon/HelpIcon/HelpIcon.less
Labels: semver-patch

#904 BookIcon, ChatIcon, and EnvelopeIcon
  src/components/Icon/BookIcon/BookIcon.jsx
  src/components/Icon/BookIcon/BookIcon.spec.jsx
  src/components/Icon/BookIcon/__snapshots__/BookIcon.spec.jsx.snap
  src/components/Icon/BookIcon/examples/1.default.jsx
  src/components/Icon/BookIcon/examples/2.clickable.jsx
  src/components/Icon/BookIcon/examples/3.disabled.jsx
  src/components/Icon/ChatIcon/ChatIcon.jsx
  src/components/Icon/ChatIcon/ChatIcon.spec.jsx
  src/components/Icon/ChatIcon/__snapshots__/ChatIcon.spec.jsx.snap
  src/components/Icon/ChatIcon/examples/1.default.jsx
  src/components/Icon/ChatIcon/examples/2.clickable.jsx
  src/components/Icon/ChatIcon/examples/3.disabled.jsx
  src/components/Icon/EnvelopeIcon/EnvelopeIcon.jsx
  src/components/Icon/EnvelopeIcon/EnvelopeIcon.spec.jsx
  src/components/Icon/EnvelopeIcon/__snapshots__/EnvelopeIcon.spec.jsx.snap
  src/components/Icon/EnvelopeIcon/examples/1.default.jsx
  src/components/Icon/EnvelopeIcon/examples/2.clickable.jsx
  src/components/Icon/EnvelopeIcon/examples/3.disabled.jsx
  src/index.js
Labels: semver-minor

#907 Add more bottom/right margin to parent tags, reduce parent tag height…
  src/components/Tag/Tag.less
Labels: semver-patch

#908 add new docs and workflow with Storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/lucid-docs-addon/ExampleCode.js
  .storybook/lucid-docs-addon/PropTypes.js
  .storybook/lucid-docs-addon/index.js
  .storybook/lucid-docs-addon/register.js
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/webpack.config.js
  docs/LucidLogo.js
  docs/child-components.md
  docs/computed-props.md
  docs/examples/Accordion.stories.js
  docs/examples/Accordion/onSelect.js
  docs/hybrid-components.md
  docs/index.stories.js
  docs/intro.md
  docs/load-components.js
  docs/load-icons.js
  gulp/docs.js
  gulpfile.js
  package.json
  scripts/docs-upload-gh.sh
  src/components/BarChart/examples/05.limited-ticks.jsx
  src/components/BarChart/examples/07.stacked.jsx
  src/components/BarChart/examples/08.unformatted-tooltips.jsx
  src/components/BarChart/examples/09.formatted-tooltip-values.jsx
  src/components/BarChart/examples/10.formatted-tooltips.jsx
  src/components/DataTable/examples/01.basic.jsx
  src/components/DataTable/examples/02.column-groups.jsx
  src/components/DataTable/examples/03.selectable-and-navigable-rows.jsx
  src/components/DataTable/examples/04.interactive-table.jsx
  src/components/DataTable/examples/05.disabled-rows.jsx
  src/components/DataTable/examples/10.min-rows.jsx
  src/components/DateSelect/examples/3.disabled-days.jsx
  src/components/Dialog/examples/3.large-with-rich-header.jsx
  src/components/Legend/examples/basic.jsx
  src/components/LineChart/examples/10.abbreviated-numbers.jsx
  stories/index.stories.js
  yarn.lock
Labels: semver-none
