Repository appnexus/lucid, pull requests merged in 2018-05, with the labels that each got.

#928 remove `browser` field from `package.json`
  package.json
Labels: in progress, semver-patch

#926 SidePanel
  .storybook/lucid-docs-addon/index.js
  docs/examples/SidePanel.stories.js
  docs/examples/SidePanel/WithDefaults.js
  docs/examples/SidePanel/WithHeader.js
  docs/examples/SidePanel/WithLeftPosition.js
  docs/examples/SidePanel/WithResize.js
  docs/examples/SidePanel/WithoutAnimation.js
  docs/examples/SidePanel/WithoutResize.js
  docs/index.stories.js
  docs/load-components.js
  src/components/Dialog/__snapshots__/Dialog.spec.jsx.snap
  src/components/Overlay/Overlay.jsx
  src/components/Overlay/Overlay.less
  src/components/Overlay/Overlay.spec.jsx
  src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
  src/components/SidePanel/SidePanel.jsx
  src/components/SidePanel/SidePanel.less
  src/components/SidePanel/SidePanel.spec.jsx
  src/components/SidePanel/__snapshots__/SidePanel.spec.jsx.snap
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.less
  src/components/Sidebar/__snapshots__/Sidebar.spec.jsx.snap
  src/components/SplitHorizontal/SplitHorizontal.jsx
  src/components/SplitHorizontal/SplitHorizontal.spec.jsx
  src/components/SplitHorizontal/__snapshots__/SplitHorizontal.spec.jsx.snap
  src/components/SplitVertical/SplitVertical.jsx
  src/components/SplitVertical/SplitVertical.spec.jsx
  src/components/SplitVertical/__snapshots__/SplitVertical.spec.jsx.snap
  src/components/Submarine/Submarine.less
  src/index.js
  src/styles/components.less
Labels: in progress, semver-minor

#930 Portal: pass store context to children
  src/components/Portal/Portal.jsx
Labels: semver-patch

#932 fixes #523 by changing the styles
  src/components/Dialog/Dialog.jsx
  src/components/Dialog/Dialog.less
  src/components/Dialog/__snapshots__/Dialog.spec.jsx.snap
  src/components/Dialog/examples/6.no-gutters.jsx
Labels: semver-minor

#933 Backporting #916 to the v1 branch
  src/components/AxisLabel/AxisLabel.less
  src/components/Bar/Bar.less
  src/components/Line/Line.less
  src/components/Point/Point.less
  src/components/VerticalListMenu/VerticalListMenu.less
  src/docs/containers/color-palette.less
  src/styles/mixins.less
  yarn.lock
Labels: in progress, semver-patch
