Repository appnexus/lucid, pull requests merged in 2019-08, with the labels that each got.

#1014 remove hidden overflow from body when SidePanel unmounts
  src/components/SidePanel/SidePanel.jsx
  src/components/SidePanel/SidePanel.spec.jsx
Labels: bug

#1017 add FourSquaresIcon
  docs/load-icons.js
  src/components/Icon/FourSquaresIcon/FourSquaresIcon.jsx
  src/components/Icon/FourSquaresIcon/FourSquaresIcon.spec.jsx
  src/components/Icon/FourSquaresIcon/__snapshots__/FourSquaresIcon.spec.jsx.snap
  src/components/Icon/FourSquaresIcon/examples/1.default.jsx
  src/index.js
Labels: semver-minor

#1022 Add teal to secondary colors for NotchedTag and improve color palette
  docs/color-palette.jsx
  docs/color-palette.less
  src/components/NotchedTag/NotchedTag.less
  src/styles/variables.less
Labels: semver-minor

#1026 Align SingleSelect with Abstract mocks
  src/components/ContextMenu/ContextMenu.jsx
  src/components/DropMenu/DropMenu.less
  src/components/SingleSelect/SingleSelect.jsx
  src/components/SingleSelect/SingleSelect.less
  src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
Labels: semver-patch
