Repository appnexus/lucid, pull requests merged in 2019-04, with the labels that each got.

#973 Remove path imports
  README.md
  package.json
  scripts/create-component-dev.sh
  scripts/create-component-docs.sh
  scripts/create-component-exports-transform.js
  scripts/create-component-exports.sh
  scripts/create-component-less.sh
  scripts/create-component-source.sh
  scripts/create-component.sh
  scripts/path-import-modules-exec.js
  scripts/path-import-modules.js
Labels: semver-major

#975 adds searchable single select component
  docs/load-components.js
  src/components/SearchableSingleSelect/SearchableSingleSelect.jsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.less
  src/components/SearchableSingleSelect/SearchableSingleSelect.reducers.js
  src/components/SearchableSingleSelect/SearchableSingleSelect.reducers.spec.js
  src/components/SearchableSingleSelect/SearchableSingleSelect.spec.jsx
  src/components/SearchableSingleSelect/__snapshots__/SearchableSingleSelect.spec.jsx.snap
  src/components/SearchableSingleSelect/examples/01.basic.jsx
  src/components/SearchableSingleSelect/examples/02.props.jsx
  src/components/SearchableSingleSelect/examples/03.asynchronous.jsx
  src/components/SearchableSingleSelect/examples/04.grouped-options.jsx
  src/index.js
  src/styles/components.less
Labels: semver-minor

#979 safeguard against duplicate portal ids
  src/components/ContextMenu/ContextMenu.jsx
  src/components/ContextMenu/__snapshots__/ContextMenu.spec.jsx.snap
  src/components/DropMenu/DropMenu.jsx
  src/components/DropMenu/__snapshots__/DropMenu.spec.jsx.snap
  src/components/Overlay/Overlay.jsx
  src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
  src/components/RadioGroup/RadioGroup.jsx
  src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
  src/util/style-helpers.js
  src/util/style-helpers.spec.js
  tests/init.js
Labels: semver-patch

#976 #974, #968 - Larger Icon option and larger close button on the SidePanel header
  package-lock.json
  src/components/Banner/__snapshots__/Banner.spec.jsx.snap
  src/components/Icon/CrossIcon/CrossIcon.jsx
  src/components/Icon/CrossIcon/__snapshots__/CrossIcon.spec.jsx.snap
  src/components/Icon/CrossIcon/examples/1.default.jsx
  src/components/Icon/CrossIcon/examples/2.clickable.jsx
  src/components/Icon/CrossIcon/examples/3.disabled.jsx
  src/components/Selection/__snapshots__/Selection.spec.jsx.snap
  src/components/SidePanel/SidePanel.jsx
  src/components/SidePanel/SidePanel.less
  src/components/SidePanel/__snapshots__/SidePanel.spec.jsx.snap
  src/components/Tag/__snapshots__/Tag.spec.jsx.snap
  src/components/ToolTip/__snapshots__/ToolTip.spec.jsx.snap
Labels: semver-minor
