Repository appnexus/lucid, pull requests merged in 2019-12, with the labels that each got.

#1086 Fix for users of older versions of storybook
  .storybook/lucid-docs-addon/register.js
Labels: semver-none

#1087 Improve VerticalListMenu types and make createClass more permissive
  docs/index.stories.js
  docs/load-components.js
  package-lock.json
  package.json
  src/components/ToolTip/__snapshots__/ToolTip.spec.jsx.snap
  src/components/VerticalListMenu/VerticalListMenu.tsx
  src/components/VerticalListMenu/examples/1.basic.jsx
  src/components/VerticalListMenu/examples/1.basic.tsx
  src/components/VerticalListMenu/examples/2.nested-with-expander.jsx
  src/components/VerticalListMenu/examples/2.nested-with-expander.tsx
  src/components/VerticalListMenu/examples/3.nested-full-width.jsx
  src/components/VerticalListMenu/examples/3.nested-full-width.tsx
  src/components/VerticalListMenu/examples/4.no-animations.tsx
  src/util/component-types.ts
  src/util/generic-tests.jsx
Labels: semver-patch

#1088 update to text in banner docs, added radio button labeled docs
  src/components/Banner/Banner.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButtonLabeled/RadioButtonLabeled.tsx
  src/components/RadioButtonLabeled/__snapshots__/RadioButtonLabeled.spec.jsx.snap
  src/components/RadioButtonLabeled/examples/0.interactive.jsx
  src/components/RadioButtonLabeled/examples/1.states.jsx
  src/components/RadioButtonLabeled/examples/2.label-as-child.jsx
  src/components/RadioButtonLabeled/examples/3.label-as-prop.jsx
  src/components/RadioButtonLabeled/examples/interactive.jsx
Labels: documentation

#1081 Cxp 893 add icons
  docs/load-icons.js
  src/components/Icon/GetMaximumIcon/GetMaximumIcon.spec.jsx
  src/components/Icon/GetMaximumIcon/GetMaximumIcon.tsx
  src/components/Icon/GetMaximumIcon/__snapshots__/GetMaximumIcon.spec.jsx.snap
  src/components/Icon/GetMaximumIcon/examples/1default.jsx
  src/components/Icon/HideIcon/HideIcon.spec.jsx
  src/components/Icon/HideIcon/HideIcon.tsx
  src/components/Icon/HideIcon/__snapshots__/HideIcon.spec.jsx.snap
  src/components/Icon/HideIcon/examples/1default.jsx
  src/components/Icon/SaveIcon/SaveIcon.spec.jsx
  src/components/Icon/SaveIcon/SaveIcon.tsx
  src/components/Icon/SaveIcon/__snapshots__/SaveIcon.spec.jsx.snap
  src/components/Icon/SaveIcon/examples/1default.jsx
  src/index.ts
Labels: semver-minor

#1069 Convert legend cxp 881
  .vscode/launch.json
  docs/load-components.js
  jest.config.js
  src/components/Legend/Legend.jsx
  src/components/Legend/Legend.tsx
  src/components/Legend/examples/basic.tsx
Labels: semver-minor

#1076 Accordion typescript conversion
  docs/load-components.js
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.reducers.js
  src/components/Accordion/Accordion.reducers.spec.js
  src/components/Accordion/Accordion.reducers.ts
  src/components/Accordion/Accordion.spec.jsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/examples/1.basic.tsx
  src/components/Accordion/examples/2.initial-index-set.tsx
  src/components/Accordion/examples/3.fixed-index.tsx
  src/components/Accordion/examples/4.disabled-item.tsx
  src/components/Accordion/examples/5.using-header-as-child.tsx
  src/components/ExpanderPanel/ExpanderPanel.tsx
  src/util/component-types.ts
Labels: semver-patch

#1070 Selection component typescript conversion
  docs/index.stories.js
  docs/load-components.js
  src/components/Selection/Selection.jsx
  src/components/Selection/Selection.tsx
  src/components/Selection/examples/1.kinds.tsx
  src/components/Selection/examples/2.nested.tsx
  src/components/Selection/examples/3.interactive.tsx
  src/util/component-types.ts
Labels: semver-patch

#1073 Convert vertical tabs
  .vscode/settings.json
  docs/load-components.js
  src/components/Lines/Lines.tsx
  src/components/VerticalListMenu/VerticalListMenu.tsx
  src/components/VerticalTabs/VerticalTabs.jsx
  src/components/VerticalTabs/VerticalTabs.reducers.js
  src/components/VerticalTabs/VerticalTabs.reducers.spec.js
  src/components/VerticalTabs/VerticalTabs.reducers.ts
  src/components/VerticalTabs/VerticalTabs.spec.jsx
  src/components/VerticalTabs/VerticalTabs.tsx
  src/components/VerticalTabs/__snapshots__/VerticalTabs.spec.jsx.snap
  src/components/VerticalTabs/examples/1-title-as-prop.tsx
  src/components/VerticalTabs/examples/2-title-as-child.tsx
  src/components/VerticalTabs/examples/3-complex-title-as-child.tsx
Labels: semver-minor

#1089 Cxp 805 validation state to search select fields
  src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.less
  src/components/SearchableMultiSelect/SearchableMultiSelect.spec.jsx
  src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.jsx.snap
  src/components/SearchableMultiSelect/examples/02.props.jsx
  src/components/SearchableMultiSelect/examples/08.invalid.jsx
  src/components/SearchableSelect/SearchableSelect.jsx
  src/components/SearchableSelect/SearchableSelect.less
  src/components/SearchableSelect/SearchableSelect.spec.jsx
  src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.jsx.snap
  src/components/SearchableSelect/examples/06.invalid.jsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.jsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.less
  src/components/SearchableSingleSelect/SearchableSingleSelect.spec.jsx
  src/components/SearchableSingleSelect/__snapshots__/SearchableSingleSelect.spec.jsx.snap
  src/components/SearchableSingleSelect/examples/06.invalid-option.jsx
Labels: semver-minor
