Repository appnexus/lucid, pull requests merged in 2019-10, with the labels that each got.

#1054 Fix redux util regression where `identity` was set to `noop`
  src/util/redux.spec.js
  src/util/redux.ts
Labels: semver-patch

#1044 fix hover/active/focus background styling for button links
  src/components/Button/Button.less
Labels: semver-patch

#1053 onClick is still triggered when a disabled IconSelect item is clicked
  src/components/IconSelect/IconSelect.tsx
  src/components/IconSelect/__snapshots__/IconSelect.spec.js.snap
Labels: bug

#1059 Docs consistent props order
  .storybook/lucid-docs-addon/util.js
Labels: documentation

#1061 Added BackUpArrowIcon and updated snapshots
  docs/load-icons.js
  src/components/Icon/BackUpArrowIcon/BackUpArrowIcon.spec.jsx
  src/components/Icon/BackUpArrowIcon/BackUpArrowIcon.tsx
  src/components/Icon/BackUpArrowIcon/__snapshots__/BackUpArrowIcon.spec.jsx.snap
  src/components/Icon/BackUpArrowIcon/examples/1.default.jsx
  src/index.ts
Labels: semver-minor

#1060 adjust hover colors for SuccessLightIcon and MinusCircleLightIcon
  src/components/Icon/MinusCircleIcon/MinusCircleIcon.less
  src/components/Icon/MinusCircleLightIcon/MinusCircleLightIcon.less
  src/components/Icon/MinusCircleLightIcon/__snapshots__/MinusCircleLightIcon.spec.jsx.snap
  src/components/Icon/MinusCircleLightIcon/examples/1.default.jsx
  src/components/Icon/SuccessLightIcon/SuccessLightIcon.less
  src/components/Icon/SuccessLightIcon/__snapshots__/SuccessLightIcon.spec.jsx.snap
  src/components/Icon/SuccessLightIcon/examples/1.default.jsx
  src/styles/variables.less
Labels: semver-patch
