Repository appnexus/lucid, pull requests merged in 2020-09, with the labels that each got.

#1165 Issue 1164: Omit Selection prop from DropMenuOption prop types
  src/components/DropMenu/DropMenu.spec.jsx
  src/components/DropMenu/DropMenu.tsx
Labels: bug, semver-patch

#1169 BUDE-646
  CHANGELOG.md
  src/components/DraggableLineChart/DraggableLineChart.tsx
  src/components/DraggableLineChart/examples/02.ExampleWithExternalXAxisRenderProp.tsx
  src/components/Typography/Typography.tsx
  src/components/Typography/__snapshots__/Typography.spec.jsx.snap
  src/components/Typography/examples/01.variants.jsx
Labels: semver-none

#1171 BUDE-646: Fix missing line
  src/components/DraggableLineChart/DraggableLineChart.tsx
  src/components/DraggableLineChart/DraggableLineChartD3.ts
  src/components/DraggableLineChart/d3-helpers.ts
  src/components/DraggableLineChart/examples/02.ExampleWithExternalXAxisRenderProp.tsx
Labels: semver-none

#1172 Cxp 1274 1424 four icons
  CHANGELOG.md
  docs/load-icons.js
  src/components/Button/Button.less
  src/components/ContextMenu/ContextMenu.spec.jsx
  src/components/Icon/HostedIcon/HostedIcon.spec.js
  src/components/Icon/HostedIcon/HostedIcon.tsx
  src/components/Icon/HostedIcon/__snapshots__/HostedIcon.spec.js.snap
  src/components/Icon/HostedIcon/examples/1.default.jsx
  src/components/Icon/LightbulbIcon/LightbulbIcon.spec.js
  src/components/Icon/LightbulbIcon/LightbulbIcon.tsx
  src/components/Icon/LightbulbIcon/__snapshots__/LightbulbIcon.spec.js.snap
  src/components/Icon/LightbulbIcon/examples/1.default.jsx
  src/components/Icon/ShareIcon/ShareIcon.spec.js
  src/components/Icon/ShareIcon/ShareIcon.tsx
  src/components/Icon/ShareIcon/__snapshots__/ShareIcon.spec.js.snap
  src/components/Icon/ShareIcon/examples/1.default.jsx
  src/components/Icon/WrenchIcon/WrenchIcon.spec.js
  src/components/Icon/WrenchIcon/WrenchIcon.tsx
  src/components/Icon/WrenchIcon/__snapshots__/WrenchIcon.spec.js.snap
  src/components/Icon/WrenchIcon/examples/1.default.jsx
  src/index.ts
Labels: semver-minor
