Repository appnexus/lucid, pull requests merged in 2020-03, with the labels that each got.

#1133 Add RadioGroup docs - remove content from RadioButtonLabeled example
  src/components/RadioButtonLabeled/examples/0.interactive.jsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
  src/components/RadioGroup/examples/0.stateful.tsx
  src/components/RadioGroup/examples/1.is-disabled.tsx
  src/components/RadioGroup/examples/2.nested-select.tsx
  src/components/RadioGroup/examples/3.selected-index-as-prop.tsx
  src/components/RadioGroup/examples/4.selected-index-from-child.tsx
  src/components/RadioGroup/examples/5.default-props.tsx
  src/components/RadioGroup/examples/nested-select.tsx
Labels: documentation, semver-none

#1135 add check for xandr font
  docs/index.less
  docs/index.stories.js
  docs/xandr-font-faces.less
  package-lock.json
Labels: semver-minor

#1136 TXP-127 add vertical orientation to dots icon
  src/components/DraggableList/__snapshots__/DraggableList.spec.jsx.snap
  src/components/Icon/DotsIcon/DotsIcon.tsx
  src/components/Icon/DotsIcon/__snapshots__/DotsIcon.spec.jsx.snap
  src/components/Icon/DotsIcon/examples/1.default.jsx
Labels: semver-minor

#1130 ResponsiveGrid component
  docs/load-components.js
  src/components/ResponsiveGrid/ResponsiveGrid.less
  src/components/ResponsiveGrid/ResponsiveGrid.spec.jsx
  src/components/ResponsiveGrid/ResponsiveGrid.tsx
  src/components/ResponsiveGrid/__snapshots__/ResponsiveGrid.spec.jsx.snap
  src/components/ResponsiveGrid/examples/01-basic.tsx
  src/components/ResponsiveGrid/examples/02-with-custom-breakpoints.tsx
  src/components/SidePanel/__snapshots__/SidePanel.spec.jsx.snap
  src/components/SidePanel/examples/09.with-responsive-grid.tsx
  src/index.ts
  src/styles/components.less
Labels: semver-minor

#1134 Feature/cxp 693 ts convert bars
  src/components/Bars/Bars copy.jsx
  src/components/Bars/Bars.tsx
  src/components/Bars/__snapshots__/Bars.spec.jsx.snap
  src/components/Bars/examples/01.basic.tsx
  src/components/Bars/examples/02.custom-colors.tsx
  src/components/PieChart/PieChart.tsx
Labels: semver-minor

#1139 Feature/cxp 1085 add new hamburger icon
  docs/load-components.js
  docs/load-icons.js
  src/components/Icon/HamburgerMenuIcon/HamburgerMenuIcon.spec.jsx
  src/components/Icon/HamburgerMenuIcon/HamburgerMenuIcon.tsx
  src/components/Icon/HamburgerMenuIcon/__snapshots__/HamburgerMenuIcon.spec.jsx.snap
  src/components/Icon/HamburgerMenuIcon/examples/1.default.jsx
  src/components/Icon/HamburgerMenuIcon/icon_menu.svg
  src/index.ts
Labels: semver-minor

#1141 Add html attributes to tabs component
  src/components/Tabs/Tabs.tsx
Labels: semver-patch, types

#1142 Feature/cxp 1080 update table cursor icon
  src/components/Table/Table.less
  src/components/Tag/examples/01.basic.jsx
Labels: bug, semver-none

#1145 Feature/cxp 880 ts convert linechart
  src/components/Axis/Axis.tsx
  src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
  src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
  src/components/EmptyStateWrapper/EmptyStateWrapper.tsx
  src/components/LineChart/LineChart copy.jsx
  src/components/LineChart/LineChart.tsx
  src/components/LineChart/__snapshots__/LineChart.spec.jsx.snap
  src/components/LineChart/examples/01.basic.tsx
  src/components/LineChart/examples/02.responsive.tsx
  src/components/LineChart/examples/03.multi.tsx
  src/components/LineChart/examples/04.multi-with-legend.tsx
  src/components/LineChart/examples/05.stacked.tsx
  src/components/LineChart/examples/06.dual-axis.tsx
  src/components/LineChart/examples/07.all-the-things.tsx
  src/components/LineChart/examples/08.stacked-single-series-with-formatters.tsx
  src/components/LineChart/examples/09.stacked-monochrome-no-shapes.tsx
  src/components/LineChart/examples/10.abbreviated-numbers.tsx
  src/components/LineChart/examples/11.color-offset.tsx
  src/components/LineChart/examples/12.empty.tsx
  src/components/LineChart/examples/13.empty-with-custom-title-and-body.tsx
  src/components/LineChart/examples/14.empty-with-button.tsx
  src/components/LineChart/examples/15.loading.tsx
  src/components/LineChart/examples/16.fine-grained-ticks.tsx
  src/components/Lines/Lines.tsx
  src/components/Points/Points.tsx
  src/util/chart-helpers.ts
  src/util/component-types.ts
Labels: semver-minor, types

#1144 Use donutWidth prop to control width of a donut chart
  src/components/PieChart/PieChart.tsx
Labels: semver-none
