Repository appnexus/lucid, pull requests merged in 2020-02, with the labels that each got.

#1122 Cxp 289/keep loading indicator viewable
  src/components/DataTable/DataTable.jsx
  src/components/DataTable/DataTable.spec.jsx
  src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
  src/components/DataTable/examples/09.empty-with-anchored-message.jsx
  src/components/DataTable/examples/10.loading.jsx
  src/components/DataTable/examples/11.loading-with-anchored-message.jsx
  src/components/DataTable/examples/12.min-rows.jsx
  src/components/DataTable/examples/13.fixed-headers.jsx
  src/components/DataTable/examples/14.resizable-fixed-headers-table.jsx
  src/components/EmptyStateWrapper/EmptyStateWrapper copy.jsx
  src/components/EmptyStateWrapper/EmptyStateWrapper.tsx
  src/components/LoadingIndicator/LoadingIndicator.tsx
  src/components/LoadingIndicator/__snapshots__/LoadingIndicator.spec.jsx.snap
  src/components/OverlayWrapper/OverlayWrapper.less
  src/components/OverlayWrapper/OverlayWrapper.spec.jsx
  src/components/OverlayWrapper/OverlayWrapper.tsx
Labels: semver-minor

#1117 Cxp 938/replace get initial state in SingleSelect, SearchableSelect, SearchableSingleSelect, SearchableMultiSelect
  src/components/DropMenu/DropMenu.tsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
  src/components/SearchableSelect/SearchableSelect.tsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.tsx
  src/components/SingleSelect/SingleSelect.tsx
Labels: semver-patch

#1119 Fix font loading
  README.md
  docs/index.less
  src/index.less
Labels: semver-none

#1115 Feature/cxp 929 storybook extensions
  CONTRIBUTING.md
  docs/load-components.js
  docs/load-icons.js
Labels: semver-none

#1126 add div props to radio button labeled
  src/components/RadioButtonLabeled/RadioButtonLabeled.tsx
Labels: semver-patch

#1124 Feature/cxp 944 946 video icons
  docs/load-icons.js
  src/components/Icon/VideoLiveIcon/VideoLiveIcon.spec.jsx
  src/components/Icon/VideoLiveIcon/VideoLiveIcon.tsx
  src/components/Icon/VideoLiveIcon/__snapshots__/VideoLiveIcon.spec.jsx.snap
  src/components/Icon/VideoLiveIcon/examples/1.default.jsx
  src/components/Icon/VideoLiveIcon/icon_VideoLive.svg
  src/components/Icon/VideoLongIcon/VideoLongIcon.spec.jsx
  src/components/Icon/VideoLongIcon/VideoLongIcon.tsx
  src/components/Icon/VideoLongIcon/__snapshots__/VideoLongIcon.spec.jsx.snap
  src/components/Icon/VideoLongIcon/examples/1.default.tsx
  src/components/Icon/VideoLongIcon/icon_VideoLong.svg
  src/components/Icon/VideoOnDemandIcon/VideoOnDemandIcon.spec.jsx
  src/components/Icon/VideoOnDemandIcon/VideoOnDemandIcon.tsx
  src/components/Icon/VideoOnDemandIcon/__snapshots__/VideoOnDemandIcon.spec.jsx.snap
  src/components/Icon/VideoOnDemandIcon/examples/1.default.jsx
  src/components/Icon/VideoOnDemandIcon/icon_VideoOnDemand.svg
  src/components/Icon/VideoShortIcon/VideoShortIcon.spec.jsx
  src/components/Icon/VideoShortIcon/VideoShortIcon.tsx
  src/components/Icon/VideoShortIcon/__snapshots__/VideoShortIcon.spec.jsx.snap
  src/components/Icon/VideoShortIcon/examples/1.default.tsx
  src/components/Icon/VideoShortIcon/icon_VideoShort.svg
  src/index.ts
Labels: semver-minor

#1123 Feature/cxp-873 TypeScript convert table component
  src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
  src/components/DragCaptureZone/DragCaptureZone.tsx
  src/components/Panel/__snapshots__/Panel.spec.jsx.snap
  src/components/ScrollTable/__snapshots__/ScrollTable.spec.jsx.snap
  src/components/Table/Table.jsx
  src/components/Table/Table.less
  src/components/Table/Table.tsx
  src/components/Table/__snapshots__/Table.spec.jsx.snap
  src/components/Table/examples/1.standard.tsx
  src/components/Table/examples/2.gray-header.tsx
  src/components/Table/examples/3.compressed.tsx
  src/components/Table/examples/4.with-border.tsx
  src/components/Table/examples/5.with-empty-column.tsx
  src/components/Table/examples/6.no-hover.tsx
  src/index.ts
Labels: semver-minor, types

#1131 Tag-docs
  src/components/SingleSelect/examples/05.disabled-options.tsx
  src/components/SingleSelect/examples/06.disabled-select.tsx
  src/components/SingleSelect/examples/09.rich-content.tsx
  src/components/SingleSelect/examples/12.stateless.tsx
  src/components/SingleSelect/examples/13.invisible.tsx
  src/components/Tag/Tag.tsx
  src/components/Tag/__snapshots__/Tag.spec.jsx.snap
  src/components/Tag/examples/01.basic.jsx
  src/components/Tag/examples/01.default.jsx
  src/components/Tag/examples/02.nested.jsx
  src/components/Tag/examples/03.double-nested.jsx
  src/components/Tag/examples/04.interactive.jsx
  src/components/Tag/examples/05.colors.jsx
Labels: documentation, semver-none

#1127 revised Releasing.md instructions
  CHANGELOG.md
  README.md
  RELEASING.md
Labels: documentation, semver-none

#1129 Feature/cxp 874 ts convert scrolltable
  CHANGELOG.md
  src/components/ScrollTable/ScrollTable.jsx
  src/components/ScrollTable/ScrollTable.tsx
  src/components/ScrollTable/__snapshots__/ScrollTable.spec.jsx.snap
  src/components/ScrollTable/examples/01.standard.tsx
  src/components/ScrollTable/examples/02.with-border.tsx
  src/components/ScrollTable/examples/03.set-width-and-height.tsx
  src/components/ScrollTable/examples/04.full-width.tsx
  src/components/ScrollTable/examples/05.set-table-width.tsx
  src/components/Table/Table.tsx
  src/index.ts
Labels: semver-minor, types
