Repository appnexus/lucid, pull requests merged in 2020-01, with the labels that each got.

#1091 add creative icon for icon color variation docs section
  docs/index.stories.js
Labels: semver-patch

#1094 Radio group typescript conversion
  docs/load-components.js
  src/components/ContextMenu/__snapshots__/ContextMenu.spec.jsx.snap
  src/components/DropMenu/__snapshots__/DropMenu.spec.jsx.snap
  src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioGroup/RadioGroup.jsx
  src/components/RadioGroup/RadioGroup.reducers.js
  src/components/RadioGroup/RadioGroup.reducers.ts
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
  src/components/RadioGroup/examples/default-props.tsx
  src/components/RadioGroup/examples/is-disabled.tsx
  src/components/RadioGroup/examples/nested-select.tsx
  src/components/RadioGroup/examples/selected-index-as-prop.tsx
  src/components/RadioGroup/examples/selected-index-from-child.tsx
  src/components/RadioGroup/examples/stateful.tsx
  src/util/component-types.ts
Labels: semver-minor

#1092 TypeScript convert paginator (869) and singleselect (877)
  docs/load-components.js
  package-lock.json
  src/components/Dialog/__snapshots__/Dialog.spec.jsx.snap
  src/components/DropMenu/DropMenu.tsx
  src/components/DropMenu/__snapshots__/DropMenu.spec.jsx.snap
  src/components/Paginator/Paginator.jsx
  src/components/Paginator/Paginator.reducers.spec.js
  src/components/Paginator/Paginator.reducers.ts
  src/components/Paginator/Paginator.selectors.spec.js
  src/components/Paginator/Paginator.selectors.ts
  src/components/Paginator/Paginator.spec.jsx
  src/components/Paginator/Paginator.tsx
  src/components/Paginator/__snapshots__/Paginator.spec.jsx.snap
  src/components/Paginator/examples/1.basic.tsx
  src/components/Paginator/examples/2.page-size-selector.tsx
  src/components/Paginator/examples/3.disabled.tsx
  src/components/Paginator/examples/4.show-object-count.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
  src/components/SearchField/__snapshots__/SearchField.spec.jsx.snap
  src/components/SingleSelect/SingleSelect.reducers.ts
  src/components/SingleSelect/SingleSelect.spec.jsx
  src/components/SingleSelect/SingleSelect.tsx
  src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
  src/components/SingleSelect/examples/01.basic.tsx
  src/components/SingleSelect/examples/02.named-options.tsx
  src/components/SingleSelect/examples/03.formatted-options.tsx
  src/components/SingleSelect/examples/04.grouped-options.tsx
  src/components/SingleSelect/examples/05.disabled-options.tsx
  src/components/SingleSelect/examples/06.disabled-select.tsx
  src/components/SingleSelect/examples/07.no-unselect.tsx
  src/components/SingleSelect/examples/08.max-menu-height.tsx
  src/components/SingleSelect/examples/09.rich-content.tsx
  src/components/SingleSelect/examples/10.no-selection-highlighting.tsx
  src/components/SingleSelect/examples/11.array-options.tsx
  src/components/SingleSelect/examples/12.stateless.tsx
  src/components/SingleSelect/examples/13.invisible.tsx
  src/components/SingleSelect/examples/14.invisible-and-disabled.tsx
  src/components/TextField/TextField.reducers.ts
  src/components/TextField/TextField.tsx
  src/components/TextFieldValidated/__snapshots__/TextFieldValidated.spec.jsx.snap
  src/components/Validation/__snapshots__/Validation.spec.jsx.snap
  src/index.ts
  src/util/state-management.ts
Labels: semver-patch, types

#1107 Update Pull Request Template
  PULL_REQUEST_TEMPLATE.md
Labels: documentation, semver-none

#1097 Feature/cxp 871 ts convert axislabel
  docs/load-components.js
  src/components/Axis/Axis.tsx
  src/components/AxisLabel/AxisLabel.jsx
  src/components/AxisLabel/AxisLabel.tsx
  src/components/AxisLabel/examples/basic.tsx
Labels: semver-patch, types

#1093 CXP-897 fix broken escape characters
  src/components/DropMenu/DropMenu.tsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
  src/components/SearchableSelect/SearchableSelect.jsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.jsx
  src/components/SingleSelect/SingleSelect.tsx
Labels: documentation

#1095 Cxp 876 ts convert searchable select
  docs/load-components.js
  src/components/DropMenu/DropMenu.tsx
  src/components/SearchableSelect/SearchableSelect.reducers.ts
  src/components/SearchableSelect/SearchableSelect.spec.jsx
  src/components/SearchableSelect/SearchableSelect.tsx
  src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.jsx.snap
  src/components/SearchableSelect/examples/01.basic.tsx
  src/components/SearchableSelect/examples/02.loading.tsx
  src/components/SearchableSelect/examples/03.custom-search-placeholder.tsx
  src/components/SearchableSelect/examples/04.invisible.tsx
  src/components/SearchableSelect/examples/05.formatted-options.tsx
  src/components/SearchableSelect/examples/06.invalid.tsx
  src/index.ts
Labels: semver-minor

#1101 Feature/cxp 872 ts convert emptystatewrapper
  src/components/EmptyStateWrapper/EmptyStateWrapper copy.jsx
  src/components/EmptyStateWrapper/EmptyStateWrapper.tsx
  src/components/LineChart/LineChart.spec.jsx
  src/index.ts
Labels: semver-patch

#1108 Feature/cxp 926 update typescript linter
  src/index.ts
Labels: semver-minor

#1109 Notched tag docs
  src/components/NotchedTag/NotchedTag.tsx
Labels: documentation, semver-none

#1112 Bug/release fixes for Lucid release
  src/components/RadioButtonLabeled/RadioButtonLabeled.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
  src/components/SearchableSelect/SearchableSelect.tsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.tsx
Labels: bug

#1114 Feature cxp 923 run report icon
  docs/load-icons.js
  src/components/Icon/RunReportIcon/RunReportIcon.tsx
  src/components/Icon/RunReportIcon/RunRepotIcon.spec.jsx
  src/components/Icon/RunReportIcon/__snapshots__/RunRepotIcon.spec.jsx.snap
  src/components/Icon/RunReportIcon/examples/1default.jsx
  src/index.ts
Labels: semver-minor

#1113 Feature/cxp 933 releasing doc
  RELEASING.md
Labels: semver-none
