Repository appnexus/lucid, pull requests merged in 2021-02, with the labels that each got.

#1194 Bwap 598 add skeletons to lucid
  docs/load-components.js
  package-lock.json
  package.json
  src/components/LoadingSkeletons/LoadingSkeleton.less
  src/components/LoadingSkeletons/LoadingSkeleton.spec.jsx
  src/components/LoadingSkeletons/LoadingSkeleton.tsx
  src/components/LoadingSkeletons/LoadingSkeletonsSvgUtil.ts
  src/components/LoadingSkeletons/TableLoadingSkeleton.spec.jsx
  src/components/LoadingSkeletons/TableLoadingSkeleton.tsx
  src/components/LoadingSkeletons/examples/TableLoadingSkeleton/1.default.jsx
  src/components/LoadingSkeletons/examples/TableLoadingSkeleton/2.custom-header.jsx
  src/components/LoadingSkeletons/examples/TableLoadingSkeleton/3.two-rows-three-columns.jsx
  src/index.ts
  src/styles/components.less
Labels: semver-minor

#1195 Fixing the background image for Anx-react lib
  .storybook/config.js
  src/styles/master.less
Labels: semver-minor

#1196 Updated various vulnerable dependencies and updated eslint
  .eslintrc
  package-lock.json
  package.json
  src/components/Axis/__snapshots__/Axis.spec.jsx.snap
  src/components/Bars/__snapshots__/Bars.spec.jsx.snap
  src/components/Bars/examples/03.log-scale.tsx
  src/components/CalendarMonth/CalendarMonth.tsx
  src/components/DateSelect/DateSelect.tsx
  src/components/DraggableLineChart/DraggableLineChartD3.ts
  src/components/Grid/examples/GridColumns.jsx
  src/components/Grid/examples/GutterlessGrid.jsx
  src/components/LineChart/LineChart.spec.jsx
  src/components/LineChart/LineChart.tsx
  src/components/Lines/Lines.spec.jsx
  src/components/Lines/__snapshots__/Lines.spec.jsx.snap
  src/components/Points/Points.spec.jsx
  src/components/Points/__snapshots__/Points.spec.jsx.snap
  src/components/Table/Table.tsx
  src/test-entry.js
  src/util/state-management.ts
Labels: semver-patch

#1197 feat: add TextFieldPlain
  src/components/TextField/TextField.less
  src/components/TextField/TextFieldPlain.spec.jsx
  src/components/TextField/TextFieldPlain.tsx
  src/components/TextField/examples/plain.jsx
  src/index.ts
Labels: semver-minor

#1198 Updated more vulnerable dependencies and updated linting
  .travis.yml
  jest.config.js
  package-lock.json
  package.json
  src/components/Icon/BellIcon/BellIcon.tsx
  src/components/Paginator/Paginator.reducers.spec.js
  src/components/SlidePanel/SlidePanel.spec.jsx
Labels: semver-major

#1199 Updated eslint, prettier, jest, and typescript to latest
  .editorconfig
  .eslintrc
  .eslintrc.yaml
  package-lock.json
  package.json
  src/components/PieChart/PieChart.reducers.ts
  src/components/SplitHorizontal/__snapshots__/SplitHorizontal.spec.jsx.snap
  src/components/SplitVertical/__snapshots__/SplitVertical.spec.jsx.snap
  tsconfig.json
Labels: semver-major

#1201 Migrated utils folder to typescript
  src/util/chart-helpers.spec.ts
  src/util/chart-helpers.ts
  src/util/component-types.spec.tsx
  src/util/dom-helpers.spec.ts
  src/util/dom-helpers.ts
  src/util/formatters.spec.ts
  src/util/logger.spec.ts
  src/util/redux.spec.ts
  src/util/redux.ts
  src/util/state-management.spec.tsx
  src/util/state-management.ts
  src/util/style-helpers.spec.ts
  src/util/style-helpers.ts
  src/util/text-manipulation.spec.tsx
  src/util/text-manipulation.ts
Labels: semver-major

#1202 Storybook background
  .storybook/config.js
Labels: semver-minor

#1208 BWAP-703 Added ComplexTableLoadingSkeleton
  docs/load-components.js
  src/components/Axis/__snapshots__/Axis.spec.tsx.snap
  src/components/LoadingSkeletons/ComplexTableLoadingSkeleton.spec.tsx
  src/components/LoadingSkeletons/ComplexTableLoadingSkeleton.tsx
  src/components/LoadingSkeletons/LoadingSkeletonsSvgUtil.ts
  src/components/LoadingSkeletons/examples/ComplexTableLoadingSkeleton/1.basic.tsx
  src/components/LoadingSkeletons/examples/ComplexTableLoadingSkeleton/2.add-header.tsx
  src/components/LoadingSkeletons/examples/ComplexTableLoadingSkeleton/3.three-rows-one-columns.tsx
  src/index.ts
Labels: semver-minor

#1209 BWAP-704 Added GroupLoadingSkeleton
  docs/load-components.js
  src/components/LoadingSkeletons/GroupLoadingSkeleton.spec.tsx
  src/components/LoadingSkeletons/GroupLoadingSkeleton.tsx
  src/components/LoadingSkeletons/TableLoadingSkeleton.spec.tsx
  src/components/LoadingSkeletons/TableLoadingSkeleton.tsx
  src/components/LoadingSkeletons/examples/GroupLoadingSkeleton/1.basic.tsx
  src/components/LoadingSkeletons/examples/GroupLoadingSkeleton/2.add-header.tsx
  src/components/LoadingSkeletons/examples/GroupLoadingSkeleton/3.two-rows-three-columns.tsx
  src/index.ts
Labels: semver-minor

#1205 BWAP-701 added BarChartLoadingSkeleton
  docs/load-components.js
  src/components/LoadingSkeletons/BarChartLoadingSkeleton.spec.tsx
  src/components/LoadingSkeletons/BarChartLoadingSkeleton.tsx
  src/components/LoadingSkeletons/examples/BarChartLoadingSkeleton/1.basic.tsx
  src/components/LoadingSkeletons/examples/BarChartLoadingSkeleton/2.add-header.tsx
  src/components/LoadingSkeletons/examples/BarChartLoadingSkeleton/3.two-rows-three-columns.tsx
  src/components/LoadingSkeletons/examples/TableLoadingSkeleton/2.add-header.tsx
  src/index.ts
Labels: semver-minor
