Repository appnexus/lucid, pull requests merged in 2021-08, with the labels that each got.

#1236 Migrate Checkbox stories to Storybook 6
  docs/load-components.js
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
  src/components/Checkbox/examples/interactive.tsx
  src/components/CheckboxLabeled/CheckboxLabeled.stories.tsx
  src/components/CheckboxLabeled/__snapshots__/CheckboxLabeled.spec.tsx.snap
  src/components/CheckboxLabeled/examples/0.interactive.tsx
  src/components/CheckboxLabeled/examples/1.states.tsx
  src/components/CheckboxLabeled/examples/2.label-as-child.tsx
  src/components/CheckboxLabeled/examples/3.label-as-prop.tsx
Labels: semver-minor

#1243 CXP 2137: Migrate some DataTable stories to SB6
  docs/index.stories.tsx
  package-lock.json
  package.json
  src/components/DataTable/DataTable.stories.tsx
  src/components/DataTable/DataTable.tsx
  src/components/DataTable/__snapshots__/DataTable.spec.tsx.snap
  src/components/DataTable/examples/01.basic.tsx
  src/components/DataTable/examples/02.column-groups.tsx
  src/components/DataTable/examples/03.selectable-and-navigable-rows.tsx
  src/components/DataTable/examples/05.disabled-rows.tsx
  src/components/DataTable/examples/06.empty.tsx
Labels: semver-patch

#1244 CXP-2140: Updated old react-syntax-highlighter dep to fix security issue
  package-lock.json
  package.json
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/CalendarMonth/CalendarMonth.spec.tsx
  src/components/CalendarMonth/CalendarMonth.tsx
  src/components/ContextMenu/ContextMenu.tsx
  src/components/ContextMenu/examples/3.menu-bar.tsx
  src/components/DataTable/DataTable.spec.tsx
  src/components/DataTable/examples/04.interactive-table.tsx
  src/components/DropMenu/DropMenu.tsx
  src/components/Expander/Expander.tsx
  src/components/Grid/Grid.tsx
  src/components/IconSelect/IconSelect.tsx
  src/components/InfiniteSlidePanel/InfiniteSlidePanel.tsx
  src/components/LineChart/LineChart.tsx
  src/components/NotchedTag/NotchedTag.tsx
  src/components/Paginator/Paginator.tsx
  src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
  src/components/SearchableSelect/SearchableSelect.spec.tsx
  src/components/SearchableSelect/SearchableSelect.tsx
  src/components/SearchableSingleSelect/SearchableSingleSelect.tsx
  src/components/Sidebar/Sidebar.spec.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/SingleSelect/SingleSelect.tsx
  src/components/SlidePanel/SlidePanel.tsx
  src/components/SplitVertical/SplitVertical.tsx
  src/components/StickySection/StickySection.tsx
  src/components/Table/Table.tsx
  src/components/TextField/TextField.tsx
  src/components/ToolTip/ToolTip.tsx
  src/util/chart-helpers.ts
  src/util/state-management.spec.tsx
Labels: semver-patch

#1246 Cxp 2149 bug react syntax highlighter paths
  .storybook/lucid-docs-addon/ChildComponents.tsx
  .storybook/lucid-docs-addon/PropTypes.tsx
  .storybook/lucid-docs-addon/register.tsx
  docs/index.stories.tsx
Labels: bug

#1249 chore: add double chevron and pin icons
  docs/icons/load-icons.ts
  src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.less
  src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.spec.tsx
  src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.stories.tsx
  src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.tsx
  src/components/Icon/DoubleChevronIcon/__snapshots__/DoubleChevronIcon.spec.tsx.snap
  src/components/Icon/Icon.tsx
  src/components/Icon/PinIcon/PinIcon.less
  src/components/Icon/PinIcon/PinIcon.spec.tsx
  src/components/Icon/PinIcon/PinIcon.stories.tsx
  src/components/Icon/PinIcon/PinIcon.tsx
  src/components/Icon/PinIcon/__snapshots__/PinIcon.spec.tsx.snap
  src/index.ts
  src/styles/components.less
  src/util/component-types.ts
Labels: semver-minor
